### ISSUE TITLE
Don't sort @keyframes properties

### ISSUE THREAD

**Issue by enzo-mourany** [enzo-mourany/css-property-sorter#1]
Sort.ts don't have to sort @keyframes properties, like on this example : 

### Before : 

```css
section
{
        min-height: 100vh;
	justify-content: center;
	align-items: center;
	display: flex;
	background: #1c1c25;
}

@keyframes identifier
{
	0%
	{
		transform: translateX(-100%);
	}
	100%
	{
		transform: translateX(0);
	}
}
````

### After

```css
section
{
	display: flex;
	justify-content: center;
	align-items: center;
        min-height: 100vh;
	background: #1c1c25;
}

@keyframes identifier
{
	0%
	{
		transform: translateX(-100%);
	}
	100%
	{
		transform: translateX(0);
	}
}
```

The keyframes part must remain as it is after sort.
